#!/usr/bin/env python3
"""Generate deterministic French guide pages from the Academy corpus."""

from __future__ import annotations

from argparse import ArgumentParser
from html import escape
from pathlib import Path
from typing import Mapping
import json
import sys
import unicodedata


WEBSITE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = WEBSITE_DIR.parent.parent
CORPUS_PATH = REPO_ROOT / "docs/academy/generated/academy-corpus.generated.json"
OUTPUT_DIR = WEBSITE_DIR / "guides"
SITE_URL = "https://brasse-bouillon.com"
GLOSSARY_ACADEMY_SLUG = "glossaire"
GENERATED_MARKER = (
    "<!-- Generated by scripts/build_guides.py. Do not edit manually. -->"
)


class GuideBuildError(RuntimeError):
    """Raised when public guide pages cannot be generated safely."""


def load_corpus(path: Path) -> Mapping[str, object]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except OSError as error:
        raise GuideBuildError(f"cannot read Academy corpus {path}: {error}") from error
    except json.JSONDecodeError as error:
        raise GuideBuildError(
            f"cannot parse Academy corpus {path}: {error.msg}"
        ) from error

    return _mapping(payload, "Academy corpus")


def public_articles(corpus: Mapping[str, object]) -> list[Mapping[str, object]]:
    raw_articles = corpus.get("articles")
    if not isinstance(raw_articles, list):
        raise GuideBuildError('Academy corpus field "articles" must be an array')

    articles: list[Mapping[str, object]] = []
    web_slugs: set[str] = set()
    for index, raw_article in enumerate(raw_articles):
        article = _mapping(raw_article, f"articles.{index}")
        metadata = _mapping(article.get("metadata"), f"articles.{index}.metadata")
        if metadata.get("category") == "glossary":
            continue
        raw_web_publication = metadata.get("webPublication")
        if raw_web_publication is None:
            continue

        web_publication = _mapping(
            raw_web_publication, f"articles.{index}.metadata.webPublication"
        )
        if web_publication.get("status") != "published":
            continue

        review = _mapping(metadata.get("review"), f"articles.{index}.metadata.review")
        if metadata.get("status") != "published":
            raise GuideBuildError(
                f"articles.{index}: public guide requires Academy status published"
            )
        if review.get("confidenceLevel") != "validated":
            raise GuideBuildError(
                f"articles.{index}: public guide requires validated review confidence"
            )

        web_slug = _required_text(
            web_publication,
            "slug",
            f"articles.{index}.metadata.webPublication",
        )
        if web_slug in web_slugs:
            raise GuideBuildError(f'duplicate public guide slug "{web_slug}"')
        web_slugs.add(web_slug)
        articles.append(article)

    return sorted(articles, key=lambda article: _web_slug(article))


def public_glossary(
    corpus: Mapping[str, object],
) -> tuple[Mapping[str, object], list[Mapping[str, object]]] | None:
    raw_articles = corpus.get("articles")
    if not isinstance(raw_articles, list):
        raise GuideBuildError('Academy corpus field "articles" must be an array')

    glossary_article: Mapping[str, object] | None = None
    for index, raw_article in enumerate(raw_articles):
        article = _mapping(raw_article, f"articles.{index}")
        if article.get("slug") == GLOSSARY_ACADEMY_SLUG:
            glossary_article = article
            break

    if glossary_article is None:
        return None

    metadata = _metadata(glossary_article)
    raw_web_publication = metadata.get("webPublication")
    if raw_web_publication is None:
        return None

    web_publication = _mapping(raw_web_publication, "glossary.metadata.webPublication")
    if web_publication.get("status") != "published":
        return None
    if metadata.get("status") != "published":
        raise GuideBuildError("glossary: public page requires Academy status published")
    review = _mapping(metadata.get("review"), "glossary.metadata.review")
    if review.get("confidenceLevel") != "validated":
        raise GuideBuildError(
            "glossary: public page requires validated review confidence"
        )

    raw_terms = corpus.get("glossaryTerms")
    if not isinstance(raw_terms, list) or not raw_terms:
        raise GuideBuildError(
            "glossary: public page requires a non-empty glossaryTerms array"
        )

    terms = [
        _mapping(raw_term, f"glossaryTerms.{index}")
        for index, raw_term in enumerate(raw_terms)
    ]
    term_slugs: set[str] = set()
    for index, term in enumerate(terms):
        slug = _required_text(term, "slug", f"glossaryTerms.{index}")
        if slug in term_slugs:
            raise GuideBuildError(f'duplicate public glossary term slug "{slug}"')
        term_slugs.add(slug)
        _required_text(term, "label", f"glossaryTerms.{index}")
        _required_text(term, "shortDefinition", f"glossaryTerms.{index}")
        _required_text(term, "detailedDefinition", f"glossaryTerms.{index}")
        _text_list(term, "aliases")
        _text_list(term, "relatedTerms")
        _mapping_list(term, "sources")

    for term in terms:
        for related_slug in _text_list(term, "relatedTerms"):
            if related_slug not in term_slugs:
                raise GuideBuildError(
                    f'glossary term "{term["slug"]}" references unknown term '
                    f'"{related_slug}"'
                )

    return glossary_article, sorted(
        terms,
        key=lambda term: _alphabetical_key(
            _required_text(term, "label", "glossary term")
        ),
    )


def expected_files(corpus: Mapping[str, object]) -> dict[Path, str]:
    articles = public_articles(corpus)
    glossary = public_glossary(corpus)
    if not articles and glossary is None:
        return {}

    article_by_academy_slug = {
        _required_text(article, "slug", "article"): article for article in articles
    }
    glossary_slugs = (
        {_required_text(term, "slug", "glossary term") for term in glossary[1]}
        if glossary is not None
        else set()
    )
    glossary_web_slug = _web_slug(glossary[0]) if glossary is not None else None
    article_web_slugs = {_web_slug(article) for article in articles}
    if glossary_web_slug in article_web_slugs:
        raise GuideBuildError(f'duplicate public guide slug "{glossary_web_slug}"')

    files = {Path("index.html"): render_hub(articles, glossary)}
    for article in articles:
        files[Path(_web_slug(article)) / "index.html"] = render_article(
            article,
            article_by_academy_slug,
            glossary_web_slug,
            glossary_slugs,
        )
    if glossary is not None:
        files[Path(glossary_web_slug) / "index.html"] = render_glossary(*glossary)
    return files


def render_hub(
    articles: list[Mapping[str, object]],
    glossary: tuple[Mapping[str, object], list[Mapping[str, object]]] | None = None,
) -> str:
    title = "Guides du brassage amateur | Brasse-Bouillon"
    description = (
        "Comprenez les ingrédients, les IBU et les techniques de brassage avec "
        "des guides pratiques, sourcés et pensés pour les brasseurs amateurs."
    )
    canonical = f"{SITE_URL}/guides/"
    cards = [_render_guide_card(article) for article in articles]
    if glossary is not None:
        cards.append(_render_glossary_card(glossary[0], len(glossary[1])))
    breadcrumb = _breadcrumb_schema(
        [("Accueil", f"{SITE_URL}/"), ("Guides", canonical)]
    )
    collection_schema = _json_ld(
        {
            "@context": "https://schema.org",
            "@type": "CollectionPage",
            "name": "Guides du brassage amateur",
            "description": description,
            "url": canonical,
            "inLanguage": "fr-FR",
            "isPartOf": {"@type": "WebSite", "url": f"{SITE_URL}/"},
        }
    )
    main = f"""
    <main id="mainContent" class="guide-shell guide-hub">
      {_visible_breadcrumb([("Accueil", "/"), ("Guides", None)])}
      <header class="guide-hero">
        <p class="guide-eyebrow">Académie Brasse-Bouillon</p>
        <h1>Guides du brassage amateur</h1>
        <p>{escape(description)}</p>
      </header>
      <section class="guide-grid" aria-label="Guides disponibles">
{"\n".join(cards)}
      </section>
    </main>"""
    return _document(
        title,
        description,
        canonical,
        main,
        [breadcrumb, collection_schema],
        og_type="website",
        guides_current=True,
    )


def render_article(
    article: Mapping[str, object],
    article_by_academy_slug: Mapping[str, Mapping[str, object]],
    glossary_web_slug: str | None = None,
    glossary_slugs: set[str] | None = None,
) -> str:
    metadata = _metadata(article)
    title = _required_text(metadata, "title", "article.metadata")
    description = _required_text(metadata, "summary", "article.metadata")
    web_slug = _web_slug(article)
    canonical = f"{SITE_URL}/guides/{web_slug}/"
    updated_at = _required_text(metadata, "updatedAt", "article.metadata")
    read_time = metadata.get("estimatedReadTimeMinutes")
    if not isinstance(read_time, int) or read_time <= 0:
        raise GuideBuildError(
            "article.metadata.estimatedReadTimeMinutes must be positive"
        )

    body = _mapping(article.get("body"), "article.body")
    raw_sections = body.get("sections")
    if not isinstance(raw_sections, list) or not raw_sections:
        raise GuideBuildError("article.body.sections must be a non-empty array")
    sections = [
        _mapping(section, f"article.body.sections.{index}")
        for index, section in enumerate(raw_sections)
    ]

    toc_items = "\n".join(
        f'          <li><a href="#{escape(_required_text(section, "id", "section"), quote=True)}">'
        f"{escape(_required_text(section, 'title', 'section'))}</a></li>"
        for section in sections
    )
    rendered_sections = "\n".join(
        _render_section(
            section,
            article_by_academy_slug,
            glossary_web_slug,
            glossary_slugs or set(),
        )
        for section in sections
    )
    learning_objectives = _text_list(metadata, "learningObjectives")
    objective_items = "\n".join(
        f"          <li>{escape(objective)}</li>" for objective in learning_objectives
    )
    sources = _mapping_list(metadata, "sources")
    source_items = "\n".join(_render_source(source) for source in sources)
    breadcrumb_items = [
        ("Accueil", f"{SITE_URL}/"),
        ("Guides", f"{SITE_URL}/guides/"),
        (title, canonical),
    ]
    schemas = [
        _breadcrumb_schema(breadcrumb_items),
        _article_schema(title, description, canonical, updated_at),
    ]
    main = f"""
    <main id="mainContent" class="guide-shell">
      {_visible_breadcrumb([("Accueil", "/"), ("Guides", "/guides/"), (title, None)])}
      <article class="guide-article">
        <header class="guide-hero">
          <p class="guide-eyebrow">Guide pratique · Niveau débutant</p>
          <h1>{escape(title)}</h1>
          <p class="guide-lead">{escape(description)}</p>
          <p class="guide-meta">
            Mis à jour le <time datetime="{escape(updated_at, quote=True)}">{escape(updated_at)}</time>
            · {read_time} min de lecture
          </p>
        </header>
        <section class="guide-objectives" aria-labelledby="objectivesTitle">
          <h2 id="objectivesTitle">Ce que tu vas comprendre</h2>
          <ul>
{objective_items}
          </ul>
        </section>
        <nav class="guide-toc" aria-labelledby="tocTitle">
          <h2 id="tocTitle">Dans ce guide</h2>
          <ol>
{toc_items}
          </ol>
        </nav>
{rendered_sections}
        <section class="guide-sources" aria-labelledby="sourcesTitle">
          <h2 id="sourcesTitle">Sources</h2>
          <ol>
{source_items}
          </ol>
        </section>
      </article>
    </main>"""
    return _document(
        title,
        description,
        canonical,
        main,
        schemas,
        og_type="article",
        guides_current=False,
    )


def render_glossary(
    article: Mapping[str, object], terms: list[Mapping[str, object]]
) -> str:
    metadata = _metadata(article)
    title = _required_text(metadata, "title", "glossary.metadata")
    description = _required_text(metadata, "summary", "glossary.metadata")
    web_slug = _web_slug(article)
    canonical = f"{SITE_URL}/guides/{web_slug}/"
    term_by_slug = {
        _required_text(term, "slug", "glossary term"): term for term in terms
    }
    grouped_terms: dict[str, list[Mapping[str, object]]] = {}
    for term in terms:
        label = _required_text(term, "label", "glossary term")
        letter = _alphabetical_key(label)[0].upper()
        grouped_terms.setdefault(letter, []).append(term)

    letter_links = "\n".join(
        f'          <li><a href="#lettre-{escape(letter.lower(), quote=True)}">'
        f"{escape(letter)}</a></li>"
        for letter in grouped_terms
    )
    groups = "\n".join(
        _render_glossary_group(letter, group, term_by_slug)
        for letter, group in grouped_terms.items()
    )
    breadcrumb_items = [
        ("Accueil", f"{SITE_URL}/"),
        ("Guides", f"{SITE_URL}/guides/"),
        (title, canonical),
    ]
    schemas = [
        _breadcrumb_schema(breadcrumb_items),
        _glossary_schema(title, description, canonical, terms),
    ]
    main = f"""
    <main id="mainContent" class="guide-shell">
      {_visible_breadcrumb([("Accueil", "/"), ("Guides", "/guides/"), (title, None)])}
      <article class="glossary-page">
        <header class="guide-hero">
          <p class="guide-eyebrow">Référence · {len(terms)} termes</p>
          <h1>{escape(title)}</h1>
          <p class="guide-lead">{escape(description)}</p>
        </header>
        <nav class="glossary-index" aria-labelledby="glossaryIndexTitle">
          <h2 id="glossaryIndexTitle">Accéder à une lettre</h2>
          <ol>
{letter_links}
          </ol>
        </nav>
{groups}
      </article>
    </main>"""
    return _document(
        f"{title} | Brasse-Bouillon",
        description,
        canonical,
        main,
        schemas,
        og_type="website",
        guides_current=False,
    )


def _document(
    title: str,
    description: str,
    canonical: str,
    main: str,
    schemas: list[str],
    *,
    og_type: str,
    guides_current: bool,
) -> str:
    escaped_title = escape(title)
    escaped_description = escape(description, quote=True)
    escaped_canonical = escape(canonical, quote=True)
    schema_markup = "\n  ".join(schemas)
    return f"""<!DOCTYPE html>
<html lang="fr" class="no-js">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {GENERATED_MARKER}
  <title>{escaped_title}</title>
  <meta name="description" content="{escaped_description}">
  <meta name="robots" content="max-image-preview:large">
  <link rel="canonical" href="{escaped_canonical}">
  <link rel="alternate" hreflang="fr" href="{escaped_canonical}">
  <link rel="alternate" hreflang="x-default" href="{escaped_canonical}">
  <meta property="og:type" content="{escape(og_type, quote=True)}">
  <meta property="og:site_name" content="Brasse-Bouillon">
  <meta property="og:url" content="{escaped_canonical}">
  <meta property="og:title" content="{escape(title, quote=True)}">
  <meta property="og:description" content="{escaped_description}">
  <meta property="og:image" content="{SITE_URL}/og-image.png?v=20260710">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="Brasse-Bouillon, guides du brassage amateur">
  <meta property="og:locale" content="fr_FR">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:url" content="{escaped_canonical}">
  <meta name="twitter:title" content="{escape(title, quote=True)}">
  <meta name="twitter:description" content="{escaped_description}">
  <meta name="twitter:image" content="{SITE_URL}/og-image.png?v=20260710">
  <link rel="icon" href="/favicon.ico">
  <link rel="stylesheet" href="/fonts.css?v=20260526">
  <link rel="stylesheet" href="/site.css?v=20260727-2">
  {schema_markup}
</head>
<body class="guide-page">
  <a class="skip-link" href="#mainContent">Aller au contenu principal</a>
  <div class="bubbles" aria-hidden="true"></div>
  {_site_header(guides_current=guides_current)}
{main}
  {_site_footer()}
  <script src="/site.js?v=20260727"></script>
  <script type="module" src="/feedback-widget.js?v=20260601"></script>
</body>
</html>
"""


def _site_header(*, guides_current: bool) -> str:
    current_attribute = ' aria-current="page"' if guides_current else ""
    return f"""<header class="site-header">
    <div class="header-inner">
      <a class="header-logo" href="/" aria-label="Brasse-Bouillon — Accueil">
        <img src="/logo-icon-32.png" alt="" width="48" height="48">
        <span>Brasse-Bouillon</span>
      </a>
      <nav class="header-nav guide-nav" aria-label="Navigation principale">
        <a href="/">Accueil</a>
        <a href="/guides/"{current_attribute}>Guides</a>
        <a class="header-cta" href="/#participerFr">Rejoindre la liste d’attente</a>
      </nav>
    </div>
  </header>"""


def _site_footer() -> str:
    return """<footer class="footer guide-footer">
    <div class="footer-brand">
      <span class="footer-mark">B·B</span>
      <p>Brasse-Bouillon, l’app du brasseur amateur curieux.</p>
    </div>
    <div class="footer-links">
      <a href="/legal">Mentions légales</a>
      <a href="/privacy">Confidentialité</a>
      <a href="/cookies">Cookies</a>
      <a href="/terms">Conditions d’utilisation</a>
    </div>
  </footer>
  <aside class="responsibility-band" aria-label="Avertissement légal">
    <div class="responsibility-band__inner">
      <span class="responsibility-band__badge" aria-hidden="true">18+</span>
      <p>L’abus d’alcool est dangereux pour la santé. À consommer avec modération.</p>
    </div>
  </aside>"""


def _render_guide_card(article: Mapping[str, object]) -> str:
    metadata = _metadata(article)
    title = _required_text(metadata, "title", "article.metadata")
    summary = _required_text(metadata, "summary", "article.metadata")
    read_time = metadata.get("estimatedReadTimeMinutes")
    return f"""        <article class="guide-card">
          <p class="guide-card__meta">Débutant · {escape(str(read_time))} min</p>
          <h2><a href="/guides/{escape(_web_slug(article), quote=True)}/">{escape(title)}</a></h2>
          <p>{escape(summary)}</p>
          <a class="guide-card__link" href="/guides/{escape(_web_slug(article), quote=True)}/">Lire le guide</a>
        </article>"""


def _render_glossary_card(article: Mapping[str, object], term_count: int) -> str:
    metadata = _metadata(article)
    title = _required_text(metadata, "title", "glossary.metadata")
    summary = _required_text(metadata, "summary", "glossary.metadata")
    web_slug = _web_slug(article)
    return f"""        <article class="guide-card">
          <p class="guide-card__meta">Référence · {term_count} termes</p>
          <h2><a href="/guides/{escape(web_slug, quote=True)}/">{escape(title)}</a></h2>
          <p>{escape(summary)}</p>
          <a class="guide-card__link" href="/guides/{escape(web_slug, quote=True)}/">Consulter le glossaire</a>
        </article>"""


def _render_section(
    section: Mapping[str, object],
    article_by_academy_slug: Mapping[str, Mapping[str, object]],
    glossary_web_slug: str | None,
    glossary_slugs: set[str],
) -> str:
    section_id = _required_text(section, "id", "section")
    title = _required_text(section, "title", "section")
    raw_blocks = section.get("blocks")
    if not isinstance(raw_blocks, list):
        raise GuideBuildError(f'section "{section_id}" blocks must be an array')
    rendered_blocks = "\n".join(
        rendered
        for index, raw_block in enumerate(raw_blocks)
        if (
            rendered := _render_block(
                _mapping(raw_block, f'section "{section_id}" block {index}'),
                article_by_academy_slug,
                glossary_web_slug,
                glossary_slugs,
            )
        )
    )
    return f"""        <section class="guide-section" id="{escape(section_id, quote=True)}">
          <h2>{escape(title)}</h2>
{rendered_blocks}
        </section>"""


def _render_block(
    block: Mapping[str, object],
    article_by_academy_slug: Mapping[str, Mapping[str, object]],
    glossary_web_slug: str | None,
    glossary_slugs: set[str],
) -> str:
    block_type = _required_text(block, "type", "content block")
    if block_type == "paragraph":
        return f"          <p>{escape(_required_text(block, 'text', 'paragraph'))}</p>"
    if block_type == "definition":
        term = escape(_required_text(block, "term", "definition"))
        definition = escape(_required_text(block, "definition", "definition"))
        return f"""          <aside class="guide-note guide-note--definition">
            <h3>{term}</h3>
            <p>{definition}</p>
          </aside>"""
    if block_type == "example":
        title = escape(_required_text(block, "title", "example"))
        body = escape(_required_text(block, "body", "example"))
        return f"""          <aside class="guide-note guide-note--example">
            <h3>{title}</h3>
            <p>{body}</p>
          </aside>"""
    if block_type == "glossaryReference":
        label = escape(_required_text(block, "label", "glossaryReference"))
        term_slug = _required_text(block, "termSlug", "glossaryReference")
        if glossary_web_slug is None:
            term_markup = f"<strong>{label}</strong>"
        else:
            if term_slug not in glossary_slugs:
                raise GuideBuildError(
                    f'glossaryReference points to unknown term "{term_slug}"'
                )
            href = escape(
                f"/guides/{glossary_web_slug}/#{term_slug}",
                quote=True,
            )
            term_markup = f'<a href="{href}"><strong>{label}</strong></a>'
        return (
            '          <p class="guide-reference">Dans le glossaire de '
            f"l’Académie : {term_markup}.</p>"
        )
    if block_type == "calculatorCta":
        title = escape(_required_text(block, "title", "calculatorCta"))
        description = escape(_required_text(block, "description", "calculatorCta"))
        return f"""          <aside class="guide-cta">
            <h3>{title}</h3>
            <p>{description}</p>
            <a href="/#features">Découvrir les outils Brasse-Bouillon</a>
          </aside>"""
    if block_type == "relatedArticle":
        academy_slug = _required_text(block, "articleSlug", "relatedArticle")
        target = article_by_academy_slug.get(academy_slug)
        if target is None:
            return ""
        target_metadata = _metadata(target)
        label = escape(_required_text(target_metadata, "title", "article.metadata"))
        href = escape(f"/guides/{_web_slug(target)}/", quote=True)
        return f'          <p class="guide-related">À lire aussi : <a href="{href}">{label}</a></p>'

    raise GuideBuildError(f'unsupported public guide block type "{block_type}"')


def _render_glossary_group(
    letter: str,
    terms: list[Mapping[str, object]],
    term_by_slug: Mapping[str, Mapping[str, object]],
) -> str:
    rendered_terms = "\n".join(
        _render_glossary_term(term, term_by_slug) for term in terms
    )
    letter_id = f"lettre-{letter.lower()}"
    return f"""        <section class="glossary-group" aria-labelledby="{escape(letter_id, quote=True)}">
          <h2 id="{escape(letter_id, quote=True)}">{escape(letter)}</h2>
          <div class="glossary-list">
{rendered_terms}
          </div>
        </section>"""


def _render_glossary_term(
    term: Mapping[str, object],
    term_by_slug: Mapping[str, Mapping[str, object]],
) -> str:
    slug = _required_text(term, "slug", "glossary term")
    label = _required_text(term, "label", "glossary term")
    aliases = _text_list(term, "aliases")
    short_definition = _required_text(term, "shortDefinition", "glossary term")
    detailed_definition = _required_text(term, "detailedDefinition", "glossary term")
    related_terms = _text_list(term, "relatedTerms")
    sources = _mapping_list(term, "sources")

    alias_markup = ""
    if aliases:
        alias_markup = (
            '              <p class="glossary-term__aliases">'
            "<strong>Aussi appelé :</strong> "
            f"{escape(', '.join(aliases))}</p>\n"
        )
    related_markup = ""
    if related_terms:
        links = ", ".join(
            f'<a href="#{escape(related_slug, quote=True)}">'
            f"{escape(_required_text(term_by_slug[related_slug], 'label', 'glossary term'))}"
            "</a>"
            for related_slug in related_terms
        )
        related_markup = (
            '              <p class="glossary-term__related">'
            f"<strong>Termes liés :</strong> {links}</p>\n"
        )
    source_links = ", ".join(_render_inline_source(source) for source in sources)

    return f"""            <article class="glossary-term" id="{escape(slug, quote=True)}">
              <h3>{escape(label)}</h3>
{alias_markup}              <p class="glossary-term__summary">{escape(short_definition)}</p>
              <p>{escape(detailed_definition)}</p>
{related_markup}              <p class="glossary-term__sources"><strong>Sources :</strong> {source_links}</p>
            </article>"""


def _render_inline_source(source: Mapping[str, object]) -> str:
    title = escape(_required_text(source, "title", "source"))
    url = source.get("url")
    if isinstance(url, str) and url:
        return (
            f'<a href="{escape(url, quote=True)}" rel="noopener noreferrer">{title}</a>'
        )
    return title


def _render_source(source: Mapping[str, object]) -> str:
    title = escape(_required_text(source, "title", "source"))
    authors = _text_list(source, "authors")
    author_text = escape(", ".join(authors))
    year = source.get("year")
    details = ", ".join(part for part in (author_text, str(year or "")) if part)
    url = source.get("url")
    if isinstance(url, str) and url:
        title_markup = (
            f'<a href="{escape(url, quote=True)}" rel="noopener noreferrer">{title}</a>'
        )
    else:
        title_markup = title
    suffix = f" — {details}" if details else ""
    return f"          <li>{title_markup}{suffix}</li>"


def _visible_breadcrumb(items: list[tuple[str, str | None]]) -> str:
    rendered: list[str] = []
    for name, href in items:
        if href is None:
            rendered.append(f'<span aria-current="page">{escape(name)}</span>')
        else:
            rendered.append(f'<a href="{escape(href, quote=True)}">{escape(name)}</a>')
    return (
        '<nav class="guide-breadcrumb" aria-label="Fil d’Ariane">'
        + '<span aria-hidden="true"> / </span>'.join(rendered)
        + "</nav>"
    )


def _breadcrumb_schema(items: list[tuple[str, str]]) -> str:
    return _json_ld(
        {
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            "itemListElement": [
                {
                    "@type": "ListItem",
                    "position": position,
                    "name": name,
                    "item": url,
                }
                for position, (name, url) in enumerate(items, start=1)
            ],
        }
    )


def _article_schema(
    title: str, description: str, canonical: str, updated_at: str
) -> str:
    return _json_ld(
        {
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": title,
            "description": description,
            "url": canonical,
            "mainEntityOfPage": canonical,
            "inLanguage": "fr-FR",
            "datePublished": updated_at,
            "dateModified": updated_at,
            "author": {"@type": "Organization", "name": "Brasse-Bouillon"},
            "publisher": {
                "@type": "Organization",
                "name": "Brasse-Bouillon",
                "url": f"{SITE_URL}/",
                "logo": {
                    "@type": "ImageObject",
                    "url": f"{SITE_URL}/logo.png",
                },
            },
            "image": f"{SITE_URL}/og-image.png?v=20260710",
        }
    )


def _glossary_schema(
    title: str,
    description: str,
    canonical: str,
    terms: list[Mapping[str, object]],
) -> str:
    return _json_ld(
        {
            "@context": "https://schema.org",
            "@type": "DefinedTermSet",
            "@id": canonical,
            "name": title,
            "description": description,
            "url": canonical,
            "inLanguage": "fr-FR",
            "isPartOf": {"@type": "WebSite", "url": f"{SITE_URL}/"},
            "hasDefinedTerm": [
                {
                    "@type": "DefinedTerm",
                    "@id": (
                        f"{canonical}#{_required_text(term, 'slug', 'glossary term')}"
                    ),
                    "name": _required_text(term, "label", "glossary term"),
                    "alternateName": _text_list(term, "aliases"),
                    "description": _required_text(
                        term, "detailedDefinition", "glossary term"
                    ),
                    "inDefinedTermSet": canonical,
                }
                for term in terms
            ],
        }
    )


def _json_ld(payload: Mapping[str, object]) -> str:
    serialized = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    safe = serialized.replace("<", "\\u003c").replace(">", "\\u003e")
    return f'<script type="application/ld+json">{safe}</script>'


def _metadata(article: Mapping[str, object]) -> Mapping[str, object]:
    return _mapping(article.get("metadata"), "article.metadata")


def _web_slug(article: Mapping[str, object]) -> str:
    metadata = _metadata(article)
    web_publication = _mapping(
        metadata.get("webPublication"), "article.metadata.webPublication"
    )
    return _required_text(web_publication, "slug", "article.metadata.webPublication")


def _mapping(value: object, label: str) -> Mapping[str, object]:
    if not isinstance(value, dict):
        raise GuideBuildError(f"{label} must be an object")
    return value


def _mapping_list(
    mapping: Mapping[str, object], key: str
) -> list[Mapping[str, object]]:
    value = mapping.get(key)
    if not isinstance(value, list):
        raise GuideBuildError(f"{key} must be an array")
    return [_mapping(item, f"{key}.{index}") for index, item in enumerate(value)]


def _text_list(mapping: Mapping[str, object], key: str) -> list[str]:
    value = mapping.get(key)
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise GuideBuildError(f"{key} must be an array of strings")
    return value


def _required_text(mapping: Mapping[str, object], key: str, label: str) -> str:
    value = mapping.get(key)
    if not isinstance(value, str) or not value.strip():
        raise GuideBuildError(f"{label}.{key} must be a non-empty string")
    return value


def _alphabetical_key(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value.casefold())
    return "".join(
        character for character in normalized if not unicodedata.combining(character)
    )


def _existing_generated_files(output_dir: Path) -> set[Path]:
    if not output_dir.exists():
        return set()
    return {
        path.relative_to(output_dir)
        for path in output_dir.rglob("index.html")
        if GENERATED_MARKER in path.read_text(encoding="utf-8")
    }


def check_generated_files(output_dir: Path, files: Mapping[Path, str]) -> list[str]:
    errors: list[str] = []
    expected_paths = set(files)
    existing_paths = _existing_generated_files(output_dir)
    for relative_path, expected in files.items():
        target = output_dir / relative_path
        if not target.exists():
            errors.append(f"missing generated guide: {target}")
        elif target.read_text(encoding="utf-8") != expected:
            errors.append(f"stale generated guide: {target}")
    for extra in sorted(existing_paths - expected_paths):
        errors.append(
            f"obsolete generated guide requires removal: {output_dir / extra}"
        )
    return errors


def write_generated_files(output_dir: Path, files: Mapping[Path, str]) -> None:
    obsolete = _existing_generated_files(output_dir) - set(files)
    if obsolete:
        obsolete_list = ", ".join(str(output_dir / path) for path in sorted(obsolete))
        raise GuideBuildError(
            "refusing to delete obsolete generated guides automatically: "
            + obsolete_list
        )
    for relative_path, content in files.items():
        target = output_dir / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = ArgumentParser(description=__doc__)
    parser.add_argument("--corpus", type=Path, default=CORPUS_PATH)
    parser.add_argument("--output", type=Path, default=OUTPUT_DIR)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    try:
        files = expected_files(load_corpus(args.corpus))
        if args.check:
            errors = check_generated_files(args.output, files)
            if errors:
                for error in errors:
                    print(f"build_guides: {error}", file=sys.stderr)
                return 1
            print(f"Guide pages are up to date ({len(files)} files).")
            return 0

        write_generated_files(args.output, files)
    except GuideBuildError as error:
        print(f"build_guides: {error}", file=sys.stderr)
        return 1

    print(f"Generated {len(files)} guide files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
