#!/usr/bin/env python3
"""Regenerate the self-hosted webfonts (packages/website/fonts/ + fonts.css).

Fetches Inter and Fraunces from the Google Fonts API (latin + latin-ext
subsets only) and writes the .woff2 files plus a local fonts.css with
@font-face rules using root-absolute /fonts/… URLs. Run from the package
root: `python scripts/fetch_fonts.py`. Requires network access; a browser
User-Agent is sent because the css2 endpoint varies its response by UA.

The fonts are served locally so no visitor IP is sent to Google (RGPD). See
fonts/_source.txt for provenance and licensing.
"""

from __future__ import annotations

from pathlib import Path
import re
import urllib.request

ROOT = Path(__file__).resolve().parent.parent
FONTS_DIR = ROOT / "fonts"
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126 Safari/537.36"
)
KEEP_SUBSETS = {"latin", "latin-ext"}
FAMILIES = {
    "Inter": (
        "https://fonts.googleapis.com/css2?"
        "family=Inter:wght@400;500;600;700;800&display=swap"
    ),
    "Fraunces": (
        "https://fonts.googleapis.com/css2?"
        "family=Fraunces:opsz,wght@9..144,500;9..144,700;9..144,900&display=swap"
    ),
}
CSS_HEADER = (
    "/* Self-hosted webfonts — no external CDN (RGPD: no visitor IP sent to\n"
    "   Google). Generated by scripts/fetch_fonts.py — latin + latin-ext\n"
    "   subsets of Inter and Fraunces. Provenance/licence in fonts/_source.txt.\n"
    "   Do not edit by hand; re-run the script. */\n\n"
)


def _get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def main() -> int:
    FONTS_DIR.mkdir(exist_ok=True)
    blocks: list[str] = []
    for family, css_url in FAMILIES.items():
        css = _get(css_url).decode("utf-8")
        parts = re.split(r"/\*\s*([a-z0-9-]+)\s*\*/", css)
        i = 1
        while i + 1 < len(parts):
            subset, block = parts[i].strip(), parts[i + 1]
            i += 2
            if subset not in KEEP_SUBSETS:
                continue
            weight = re.search(r"font-weight:\s*([0-9 ]+);", block).group(1)
            weight = weight.strip().replace(" ", "-")
            url_match = re.search(
                r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)", block
            )
            if not url_match:
                continue
            fname = f"{family.lower()}-{weight}-{subset}.woff2"
            (FONTS_DIR / fname).write_bytes(_get(url_match.group(1)))
            local = re.sub(
                r"url\(https://fonts\.gstatic\.com/[^)]+\.woff2\)",
                f"url('/fonts/{fname}')",
                block,
            ).strip()
            blocks.append(local)
            print(f"  {fname}")
    (ROOT / "fonts.css").write_text(CSS_HEADER + "\n".join(blocks) + "\n")
    print(f"Wrote {len(blocks)} @font-face rules to fonts.css")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
