# ==============================================================================
# Brasse-Bouillon — Monorepo Makefile
# ==============================================================================

SONAR_CONTAINER := vsea-sonarqube
SONAR_IMAGE     := sonarqube:lts-community
SONAR_PORT      := 9000
SONAR_URL       := http://localhost:$(SONAR_PORT)

# LAN IP used so Expo Go (phone) can reach the API running on this machine.
# Detection order: macOS (ipconfig Wi-Fi en0 / Ethernet en1) → Linux
# (hostname -I) → localhost fallback. `hostname -I` does not exist on
# macOS and its pipeline exits 0 with empty output, so it cannot be the
# first probe.
LAN_IP := $(shell \
	ipconfig getifaddr en0 2>/dev/null \
	|| ipconfig getifaddr en1 2>/dev/null \
	|| (command -v hostname >/dev/null && hostname -I 2>/dev/null | awk 'NF{print $$1; exit}') \
	|| echo localhost)
LAN_IP := $(if $(strip $(LAN_IP)),$(LAN_IP),localhost)
API_PORT := 3000

.PHONY: help setup dev dev-api dev-mobile test-all lint-all \
        sonar-start sonar-stop sonar-status sonar-scan \
        docker-build docker-up docker-down docker-logs

help: ## Show this help
	@awk 'BEGIN {FS = ":.*?## "; printf "\n\033[1mUsage:\033[0m\n  make \033[36m<target>\033[0m\n"} \
	  /^## @/ {printf "\n\033[1m%s\033[0m\n", substr($$0, 5)} \
	  /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}' \
	  $(MAKEFILE_LIST)

## ============================================================================
## @Dev environment
## ============================================================================

setup: ## Bootstrap local dev — create missing .env files with the LAN IP auto-detected
	@echo "[setup] Detected LAN IP: $(LAN_IP)"
	@if [ ! -f packages/api/.env ]; then \
		echo "[setup] Creating packages/api/.env from .env.example ..."; \
		cp packages/api/.env.example packages/api/.env; \
		SECRET=$$(openssl rand -hex 32 2>/dev/null || echo "dev-secret-please-replace-me-32chars"); \
		sed -i.bak "s|JWT_SECRET=.*|JWT_SECRET=$$SECRET|" packages/api/.env && rm -f packages/api/.env.bak; \
		echo "[setup] JWT_SECRET generated."; \
	else \
		echo "[setup] packages/api/.env already exists — left untouched."; \
	fi
	@if [ ! -f packages/mobile-app/.env ]; then \
		echo "[setup] Creating packages/mobile-app/.env pointing at http://$(LAN_IP):$(API_PORT) ..."; \
		printf "# Auto-generated by make setup — API URL uses the machine LAN IP\n# so Expo Go on a phone can reach the backend.\nEXPO_PUBLIC_API_URL=http://$(LAN_IP):$(API_PORT)\nEXPO_PUBLIC_USE_DEMO_DATA=false\n" > packages/mobile-app/.env; \
	else \
		echo "[setup] packages/mobile-app/.env already exists — left untouched."; \
	fi
	@echo "[setup] Done. Next: 'make dev-api' in one terminal, 'make dev-mobile' in another."

dev-api: ## Start the NestJS API in watch mode (http://LAN_IP:3000)
	@echo "[dev-api] API will be reachable at http://$(LAN_IP):$(API_PORT)"
	npm run dev:api

dev-mobile: ## Start Expo in LAN mode (scan the QR code with Expo Go)
	@echo "[dev-mobile] Make sure your phone is on the same Wi-Fi as this machine."
	npm -w packages/mobile-app run start:lan

dev: ## Start API and Expo in parallel (Ctrl+C stops both)
	@echo "[dev] Starting API + Expo — API at http://$(LAN_IP):$(API_PORT)"
	@trap 'kill 0' INT TERM; \
		(npm run dev:api) & \
		(npm -w packages/mobile-app run start:lan) & \
		wait

test-all: ## Run mobile-app + api + beer-encyclopedia test suites
	npm run test:all
	@if [ -x packages/beer-encyclopedia/.venv/bin/pytest ]; then \
		echo "[test-all] Running beer-encyclopedia pytest ..."; \
		(cd packages/beer-encyclopedia && .venv/bin/pytest -q); \
	elif command -v pytest >/dev/null 2>&1; then \
		echo "[test-all] Running beer-encyclopedia pytest (system pytest) ..."; \
		(cd packages/beer-encyclopedia && pytest -q); \
	else \
		echo "[test-all] SKIP beer-encyclopedia — no .venv/ nor system pytest found."; \
		echo "            Run 'pip install -e \".[ml,dev]\"' in packages/beer-encyclopedia to enable."; \
	fi

lint-all: ## Run mobile-app and api linters
	npm run lint:all

## ============================================================================
## @SonarQube
## ============================================================================

sonar-start: ## Start local SonarQube server (Docker, port 9000) — creates container on first run
	@if docker ps -a --format '{{.Names}}' | grep -q '^$(SONAR_CONTAINER)$$'; then \
		echo "[sonar] Starting existing container..."; \
		docker start $(SONAR_CONTAINER); \
	else \
		echo "[sonar] Creating and starting SonarQube container..."; \
		docker run -d --name $(SONAR_CONTAINER) -p $(SONAR_PORT):9000 \
			-v ci_sonarqube_data:/opt/sonarqube/data \
			-v ci_sonarqube_extensions:/opt/sonarqube/extensions \
			-v ci_sonarqube_logs:/opt/sonarqube/logs \
			$(SONAR_IMAGE); \
	fi
	@echo "[sonar] Waiting for SonarQube to be ready at $(SONAR_URL) ..."
	@until curl -sf $(SONAR_URL)/api/system/status | grep -q '"status":"UP"'; do \
		printf '.'; sleep 3; \
	done
	@echo ""
	@echo "[sonar] SonarQube is UP → $(SONAR_URL)"

sonar-stop: ## Stop local SonarQube server (container is kept, data preserved)
	docker stop $(SONAR_CONTAINER)
	@echo "[sonar] SonarQube stopped."

sonar-status: ## Show local SonarQube server status
	@if docker ps --format '{{.Names}}' | grep -q '^$(SONAR_CONTAINER)$$'; then \
		echo "[sonar] Container: running"; \
		curl -sf $(SONAR_URL)/api/system/status && echo || echo "[sonar] HTTP not yet ready"; \
	elif docker ps -a --format '{{.Names}}' | grep -q '^$(SONAR_CONTAINER)$$'; then \
		echo "[sonar] Container: stopped (run 'make sonar-start' to resume)"; \
	else \
		echo "[sonar] Container: not found (run 'make sonar-start' to create)"; \
	fi

sonar-scan: ## Run SonarQube analysis against local server (requires SONAR_TOKEN env var)
	@if [ -z "$(SONAR_TOKEN)" ]; then \
		echo "Error: SONAR_TOKEN is required."; \
		echo "Usage: make sonar-scan SONAR_TOKEN=sqp_xxxx"; \
		exit 1; \
	fi
	SONAR_TOKEN=$(SONAR_TOKEN) bash tools/ci/sonar-scan.sh

## ============================================================================
## @Docker (API)
## ============================================================================

docker-build: ## Build the API Docker image locally (packages/api)
	docker build -t brasse-bouillon-api:local packages/api

docker-up: ## Start the API container in production mode (detached)
	docker compose -f packages/api/docker-compose.yml up -d

docker-down: ## Stop and remove the API container
	docker compose -f packages/api/docker-compose.yml down

docker-logs: ## Follow API container logs (Ctrl+C to exit)
	docker compose -f packages/api/docker-compose.yml logs -f api
