services:
  backend:
    build: .
    container_name: brasse-backend
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: brasse-db
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: brasse_bouillon
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
