import * as bcrypt from 'bcrypt';

import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

import { UserRole } from '../../common/enums/role.enum';

/**
 * User Entity
 *
 * Represents a user in the Brasse-Bouillon brewing application.
 * Handles user authentication data, profile information, account status, and role-based access.
 *
 * Database: SQLite (users table)
 * Primary Key: UUID (auto-generated)
 * Indexes: email (unique), username (unique)
 *
 * @class User
 * @decorator @Entity('users') Maps this class to the 'users' table in the database
 *
 * @example
 * // Create a new user
 * const user = new User();
 * user.email = 'john@example.com';
 * user.username = 'john_doe';
 * user.password_hash = await User.hashPassword('password123');
 * user.first_name = 'John';
 * user.last_name = 'Doe';
 * user.role = UserRole.USER; // Default role
 * user.is_active = true;
 * await userRepository.save(user);
 */
@Entity('users')
@Index(['email'], { unique: true })
@Index(['username'], { unique: true })
export class User {
  /**
   * Unique identifier for the user.
   * Auto-generated UUID ensures global uniqueness and security.
   *
   * @type {string}
   * @example "550e8400-e29b-41d4-a716-446655440000"
   */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * User's email address.
   * Must be unique across the system and is required.
   * Used for authentication and communication.
   *
   * @type {string}
   * @example "john.doe@example.com"
   */
  @Column({ type: 'varchar', length: 255, nullable: false })
  email: string;

  /**
   * User's unique username.
   * Used for login and public identification.
   * Must be between 3 and 20 characters.
   *
   * @type {string}
   * @example "john_doe_42"
   */
  @Column({ type: 'varchar', length: 100, nullable: false })
  username: string;

  /**
   * Hashed password using bcrypt algorithm.
   * **IMPORTANT**: Never store plain text passwords. Always hash before storing.
   * Use the hashPassword() static method to generate this value.
   *
   * @type {string}
   * @see User.hashPassword() for password hashing
   * @see User.validatePassword() for password verification
   *
   * @security Bcrypt hash with 10 salt rounds
   */
  @Column({ type: 'varchar', length: 255, nullable: false })
  password_hash: string;

  /**
   * User's first name (optional).
   * Used in user profile and communication.
   *
   * @type {string | null}
   * @example "John"
   */
  @Column({ type: 'varchar', length: 255, nullable: true })
  first_name: string;

  /**
   * User's last name (optional).
   * Used in user profile and communication.
   *
   * @type {string | null}
   * @example "Doe"
   */
  @Column({ type: 'varchar', length: 255, nullable: true })
  last_name: string;

  /**
   * User role for Role-Based Access Control (RBAC)
   *
   * Determines what operations the user can perform:
   * - ADMIN: Full access to all resources (manage users, moderate content)
   * - USER: Limited access (own resources only, can view public data)
   * - MODERATOR: Can moderate content and view reports
   *
   * @type {UserRole}
   * @enum {string} 'admin' | 'user' | 'moderator'
   * @default UserRole.USER
   *
   * @example
   * user.role = UserRole.ADMIN;      // Make admin
   * user.role = UserRole.MODERATOR;  // Make moderator
   * user.role = UserRole.USER;       // Regular user (default)
   *
   * @see UserRole enum for available roles
   * @see RolesGuard for role enforcement
   * @see @Roles() decorator for route protection
   */
  @Column({
    type: 'varchar',
    length: 20,
    enum: UserRole,
    default: UserRole.USER,
  })
  role: UserRole = UserRole.USER;

  /**
   * Timestamp when the user account was created.
   * Auto-generated by TypeORM and never changes.
   *
   * @type {Date}
   * @readonly
   */
  @CreateDateColumn({ type: 'datetime', default: () => 'CURRENT_TIMESTAMP' })
  created_at: Date;

  /**
   * Timestamp of the last user account modification.
   * Auto-updated by TypeORM on every change.
   *
   * @type {Date}
   */
  @UpdateDateColumn({ type: 'datetime', default: () => 'CURRENT_TIMESTAMP' })
  updated_at: Date;

  /**
   * Account status flag.
   * Determines if the user account is active and can be used.
   * Defaults to true - new accounts are active. Set to false to disable account.
   *
   * @type {boolean}
   * @default true
   *
   * @example
   * user.is_active = true;  // Account is active
   * user.is_active = false; // Account is disabled (deactivated)
   */
  @Column({ type: 'boolean', default: true })
  is_active: boolean;

  /**
   * Validates a plain text password against the stored hashed password.
   * Uses bcrypt.compare() for secure comparison that resists timing attacks.
   *
   * @async
   * @param {string} password - The plain text password to verify
   * @returns {Promise<boolean>} True if password matches, false otherwise
   *
   * @example
   * const user = await userRepository.findOne({ where: { id: userId } });
   * const isValid = await user.validatePassword('myPassword123');
   * if (isValid) {
   *   // Login successful - generate JWT token
   * } else {
   *   // Login failed - invalid credentials
   * }
   *
   * @security Resistant to timing attacks thanks to bcrypt
   */
  async validatePassword(password: string): Promise<boolean> {
    return bcrypt.compare(password, this.password_hash);
  }

  /**
   * Hashes a plain text password using bcrypt algorithm.
   * Must be called before storing a password in the database.
   *
   * **Security Notes**:
   * - Salt rounds: 10 (recommended security/performance balance)
   * - Each call produces a different hash even for the same password
   * - Never expose the plain password after hashing
   * - Use this method in UserService during user creation and password updates
   *
   * @static
   * @async
   * @param {string} password - Plain text password to hash
   * @returns {Promise<string>} The hashed password ready for database storage
   * @throws {Error} If bcrypt hash fails (rare, usually due to invalid input)
   *
   * @example
   * // During user registration
   * const passwordHash = await User.hashPassword('securePassword123!');
   * const newUser = userRepository.create({
   *   email: 'user@example.com',
   *   username: 'username',
   *   password_hash: passwordHash, // Store the hash, not the plain password
   *   role: UserRole.USER,
   * });
   * await userRepository.save(newUser);
   *
   * @security Bcrypt: Industry-standard for password hashing
   */
  static async hashPassword(password: string): Promise<string> {
    const saltRounds = 10;
    return bcrypt.hash(password, saltRounds);
  }
}
