/**
 * Hop catalog — 60 most common brewing varieties.
 * Alpha acid ranges are approximate and may vary by harvest.
 * Source: various commercial brewing references (BYO, BrewUnited, Hop Growers of America).
 *
 * NOTE: This catalog is a local snapshot intended for offline/demo use.
 * A future iteration will fetch varieties from the brasse-bouillon backend API.
 */

export type Hop = {
  /** Variety name */
  name: string;
  /** Minimum alpha acid percentage */
  aaMin: number;
  /** Maximum alpha acid percentage */
  aaMax: number;
  /** Typical aroma descriptors (French) */
  aroma: string;
  /** Country / region of origin */
  origin: string;
  /** Primary use: bittering-focused, aroma-focused, or dual purpose */
  use: "bittering" | "aroma" | "dual";
};

export const hopCatalog: Hop[] = [
  // ─── USA ──────────────────────────────────────────────────────────────────
  {
    name: "Amarillo",
    aaMin: 8,
    aaMax: 11,
    aroma: "agrumes, pamplemousse, floral",
    origin: "USA",
    use: "aroma",
  },
  {
    name: "Bravo",
    aaMin: 14,
    aaMax: 17,
    aroma: "fruité, chocolat, vanille",
    origin: "USA",
    use: "bittering",
  },
  {
    name: "Cascade",
    aaMin: 4.5,
    aaMax: 7,
    aroma: "agrumes, floral, résineux",
    origin: "USA",
    use: "dual",
  },
  {
    name: "Centennial",
    aaMin: 9,
    aaMax: 12,
    aroma: "agrumes, floral, résineux",
    origin: "USA",
    use: "dual",
  },
  {
    name: "Chinook",
    aaMin: 12,
    aaMax: 14,
    aroma: "résineux, pin, épicé",
    origin: "USA",
    use: "bittering",
  },
  {
    name: "Citra",
    aaMin: 11,
    aaMax: 14,
    aroma: "tropical, agrumes, fruit de la passion",
    origin: "USA",
    use: "aroma",
  },
  {
    name: "Cluster",
    aaMin: 5.5,
    aaMax: 8.5,
    aroma: "floral, épicé, fruité",
    origin: "USA",
    use: "bittering",
  },
  {
    name: "Columbus (CTZ)",
    aaMin: 14,
    aaMax: 18,
    aroma: "terreux, épicé, résineux",
    origin: "USA",
    use: "bittering",
  },
  {
    name: "Crystal",
    aaMin: 3.5,
    aaMax: 5.5,
    aroma: "floral, épicé, herbacé",
    origin: "USA",
    use: "aroma",
  },
  {
    name: "El Dorado",
    aaMin: 14,
    aaMax: 17,
    aroma: "tropical, poire, pastèque",
    origin: "USA",
    use: "dual",
  },
  {
    name: "Ekuanot",
    aaMin: 13,
    aaMax: 15,
    aroma: "tropical, fruits rouges, herbacé",
    origin: "USA",
    use: "aroma",
  },
  {
    name: "Galena",
    aaMin: 12,
    aaMax: 15,
    aroma: "terreux, fruité, résineux",
    origin: "USA",
    use: "bittering",
  },
  {
    name: "Glacier",
    aaMin: 5,
    aaMax: 6.5,
    aroma: "fruité, pêche, agrumes",
    origin: "USA",
    use: "dual",
  },
  {
    name: "Horizon",
    aaMin: 11,
    aaMax: 13,
    aroma: "neutre, floral, léger",
    origin: "USA",
    use: "bittering",
  },
  {
    name: "Idaho 7",
    aaMin: 12,
    aaMax: 15,
    aroma: "tropical, mangue, pin",
    origin: "USA",
    use: "aroma",
  },
  {
    name: "Liberty",
    aaMin: 3,
    aaMax: 5,
    aroma: "épicé, herbacé, floral",
    origin: "USA",
    use: "aroma",
  },
  {
    name: "Millennium",
    aaMin: 14.5,
    aaMax: 16.5,
    aroma: "résineux, herbacé, neutre",
    origin: "USA",
    use: "bittering",
  },
  {
    name: "Mosaic",
    aaMin: 11.5,
    aaMax: 13.5,
    aroma: "tropical, myrtille, herbacé",
    origin: "USA",
    use: "aroma",
  },
  {
    name: "Mount Hood",
    aaMin: 5,
    aaMax: 8,
    aroma: "herbacé, épicé, floral",
    origin: "USA",
    use: "aroma",
  },
  {
    name: "Nugget",
    aaMin: 12,
    aaMax: 16,
    aroma: "herbacé, épicé, terreux",
    origin: "USA",
    use: "bittering",
  },
  {
    name: "Simcoe",
    aaMin: 12,
    aaMax: 14,
    aroma: "pin, tropical, agrumes",
    origin: "USA",
    use: "dual",
  },
  {
    name: "Sterling",
    aaMin: 6,
    aaMax: 9,
    aroma: "épicé, floral, herbacé",
    origin: "USA",
    use: "aroma",
  },
  {
    name: "Summit",
    aaMin: 17,
    aaMax: 19,
    aroma: "agrumes, ail, oignon",
    origin: "USA",
    use: "bittering",
  },
  {
    name: "Tahoma",
    aaMin: 8,
    aaMax: 11,
    aroma: "épicé, herbacé, minéral",
    origin: "USA",
    use: "dual",
  },
  {
    name: "Warrior",
    aaMin: 15,
    aaMax: 17,
    aroma: "résineux, neutre, propre",
    origin: "USA",
    use: "bittering",
  },
  {
    name: "Willamette",
    aaMin: 4,
    aaMax: 6,
    aroma: "herbacé, floral, épicé",
    origin: "USA",
    use: "aroma",
  },
  // ─── Allemagne ────────────────────────────────────────────────────────────
  {
    name: "Callista",
    aaMin: 2.5,
    aaMax: 5,
    aroma: "abricot, pêche, fruité",
    origin: "Allemagne",
    use: "aroma",
  },
  {
    name: "Hallertau Blanc",
    aaMin: 9,
    aaMax: 12,
    aroma: "tropical, agrumes, groseille blanche",
    origin: "Allemagne",
    use: "aroma",
  },
  {
    name: "Hallertau Mittelfrueh",
    aaMin: 3,
    aaMax: 5.5,
    aroma: "floral, herbacé, épicé",
    origin: "Allemagne",
    use: "aroma",
  },
  {
    name: "Hüll Melon",
    aaMin: 6.9,
    aaMax: 7.5,
    aroma: "melon, fraise, fruité",
    origin: "Allemagne",
    use: "aroma",
  },
  {
    name: "Magnum",
    aaMin: 11,
    aaMax: 16,
    aroma: "neutre, résineux, propre",
    origin: "Allemagne",
    use: "bittering",
  },
  {
    name: "Mandarina Bavaria",
    aaMin: 7,
    aaMax: 10,
    aroma: "mandarine, agrumes, fruité",
    origin: "Allemagne",
    use: "aroma",
  },
  {
    name: "Northern Brewer",
    aaMin: 8,
    aaMax: 10,
    aroma: "herbacé, résineux, terreux",
    origin: "Allemagne",
    use: "bittering",
  },
  {
    name: "Perle",
    aaMin: 7,
    aaMax: 9.5,
    aroma: "herbacé, épicé, menthe",
    origin: "Allemagne",
    use: "dual",
  },
  {
    name: "Spalt Select",
    aaMin: 3,
    aaMax: 6,
    aroma: "épicé, herbacé, floral",
    origin: "Allemagne",
    use: "aroma",
  },
  {
    name: "Tettnang",
    aaMin: 3,
    aaMax: 6,
    aroma: "herbacé, épicé, terreux",
    origin: "Allemagne",
    use: "aroma",
  },
  // ─── République Tchèque ───────────────────────────────────────────────────
  {
    name: "Saaz",
    aaMin: 2,
    aaMax: 5,
    aroma: "terreux, épicé, herbacé",
    origin: "Rép. Tchèque",
    use: "aroma",
  },
  // ─── Slovénie ─────────────────────────────────────────────────────────────
  {
    name: "Styrian Goldings",
    aaMin: 4.5,
    aaMax: 6,
    aroma: "terreux, herbacé, épicé",
    origin: "Slovénie",
    use: "aroma",
  },
  {
    name: "Styrian Wolf",
    aaMin: 13,
    aaMax: 16,
    aroma: "résineux, herbacé, terreux",
    origin: "Slovénie",
    use: "bittering",
  },
  // ─── Royaume-Uni ──────────────────────────────────────────────────────────
  {
    name: "Admiral",
    aaMin: 13,
    aaMax: 16,
    aroma: "résineux, herbacé, agrumes",
    origin: "Royaume-Uni",
    use: "bittering",
  },
  {
    name: "Bramling Cross",
    aaMin: 5,
    aaMax: 7,
    aroma: "cassis, fruits rouges, épicé",
    origin: "Royaume-Uni",
    use: "aroma",
  },
  {
    name: "Challenger",
    aaMin: 7,
    aaMax: 9,
    aroma: "épicé, herbacé, cèdre",
    origin: "Royaume-Uni",
    use: "dual",
  },
  {
    name: "East Kent Goldings",
    aaMin: 4,
    aaMax: 7,
    aroma: "floral, herbacé, miel",
    origin: "Royaume-Uni",
    use: "aroma",
  },
  {
    name: "Fuggles",
    aaMin: 3.5,
    aaMax: 6,
    aroma: "terreux, herbacé, boisé",
    origin: "Royaume-Uni",
    use: "aroma",
  },
  {
    name: "Target",
    aaMin: 9.5,
    aaMax: 12.5,
    aroma: "herbacé, épicé, agrumes",
    origin: "Royaume-Uni",
    use: "bittering",
  },
  // ─── Australie ────────────────────────────────────────────────────────────
  {
    name: "Galaxy",
    aaMin: 11,
    aaMax: 16,
    aroma: "tropical, pêche, agrumes",
    origin: "Australie",
    use: "aroma",
  },
  {
    name: "Vic Secret",
    aaMin: 14,
    aaMax: 17,
    aroma: "tropical, pin, fruit de la passion",
    origin: "Australie",
    use: "aroma",
  },
  // ─── Nouvelle-Zélande ─────────────────────────────────────────────────────
  {
    name: "Green Bullet",
    aaMin: 11,
    aaMax: 14,
    aroma: "résineux, herbacé, épicé",
    origin: "Nouvelle-Zélande",
    use: "bittering",
  },
  {
    name: "Motueka",
    aaMin: 6.5,
    aaMax: 7.5,
    aroma: "tropical, citron vert, épicé",
    origin: "Nouvelle-Zélande",
    use: "aroma",
  },
  {
    name: "Nelson Sauvin",
    aaMin: 12,
    aaMax: 13,
    aroma: "raisin blanc, tropical, fruité",
    origin: "Nouvelle-Zélande",
    use: "aroma",
  },
  {
    name: "Pacific Gem",
    aaMin: 13,
    aaMax: 15,
    aroma: "boisé, mûre, fruité",
    origin: "Nouvelle-Zélande",
    use: "bittering",
  },
  {
    name: "Pacific Jade",
    aaMin: 12,
    aaMax: 14,
    aroma: "herbacé, agrumes, épicé",
    origin: "Nouvelle-Zélande",
    use: "dual",
  },
  {
    name: "Riwaka",
    aaMin: 4.5,
    aaMax: 6.5,
    aroma: "pamplemousse, tropical, floral",
    origin: "Nouvelle-Zélande",
    use: "aroma",
  },
  {
    name: "Wai-iti",
    aaMin: 2.7,
    aaMax: 5,
    aroma: "pêche, abricot, citron",
    origin: "Nouvelle-Zélande",
    use: "aroma",
  },
  // ─── Japon ────────────────────────────────────────────────────────────────
  {
    name: "Sorachi Ace",
    aaMin: 13,
    aaMax: 16,
    aroma: "aneth, citron, herbacé",
    origin: "Japon",
    use: "aroma",
  },
  // ─── France ───────────────────────────────────────────────────────────────
  {
    name: "Aramis",
    aaMin: 7.9,
    aaMax: 8.5,
    aroma: "épicé, floral, herbacé",
    origin: "France",
    use: "dual",
  },
  {
    name: "Strisselspalt",
    aaMin: 2.5,
    aaMax: 5,
    aroma: "herbacé, épicé, légèrement fruité",
    origin: "France",
    use: "aroma",
  },
  {
    name: "Triskel",
    aaMin: 7.2,
    aaMax: 8.6,
    aroma: "fruité, floral, herbacé",
    origin: "France",
    use: "aroma",
  },
  // ─── Belgique / Autres ────────────────────────────────────────────────────
  {
    name: "Brewers Gold",
    aaMin: 7,
    aaMax: 11,
    aroma: "fruité, épicé, terreux",
    origin: "USA/Allemagne",
    use: "bittering",
  },
];

/** Returns the mid-range alpha acid value for a hop variety */
export function getHopDefaultAa(hop: Hop): number {
  return Math.round(((hop.aaMin + hop.aaMax) / 2) * 10) / 10;
}
