import * as bcrypt from 'bcrypt';

import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

/**
 * User Entity
 *
 * Represents a user in the Brasse-Bouillon brewing application.
 * Handles user authentication data, profile information, and account status.
 *
 * @class User
 * @decorator @Entity('users') Maps this class to the 'users' table in the database
 */
@Entity('users')
@Index(['email'], { unique: true })
@Index(['username'], { unique: true })
export class User {
  /**
   * Unique identifier for the user.
   * Auto-generated UUID ensures global uniqueness and security.
   *
   * @type {string}
   */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * User's email address.
   * Must be unique across the system and is required.
   * Used for authentication and communication.
   *
   * @type {string}
   * @example "john.doe@example.com"
   */
  @Column({ type: 'varchar', length: 255, nullable: false })
  email: string;

  /**
   * User's unique username.
   * Used for login and public identification.
   * Must be between 3 and 20 characters.
   *
   * @type {string}
   * @example "john_doe_42"
   */
  @Column({ type: 'varchar', length: 100, nullable: false })
  username: string;

  /**
   * Hashed password using bcrypt algorithm.
   * **IMPORTANT**: Never store plain text passwords. Always hash before storing.
   * Use the hashPassword() static method to generate this value.
   *
   * @type {string}
   * @see User.hashPassword() for password hashing
   * @see User.validatePassword() for password verification
   */
  @Column({ type: 'varchar', length: 255, nullable: false })
  password_hash: string;

  /**
   * User's first name (optional).
   * Used in user profile and communication.
   *
   * @type {string | null}
   * @example "John"
   */
  @Column({ type: 'varchar', length: 255, nullable: true })
  first_name: string;

  /**
   * User's last name (optional).
   * Used in user profile and communication.
   *
   * @type {string | null}
   * @example "Doe"
   */
  @Column({ type: 'varchar', length: 255, nullable: true })
  last_name: string;

  /**
   * Timestamp when the user account was created.
   * Auto-generated by TypeORM and never changes.
   *
   * @type {Date}
   * @readonly
   */
  @CreateDateColumn({ type: 'datetime', default: () => 'CURRENT_TIMESTAMP' })
  created_at: Date;

  /**
   * Timestamp of the last user account modification.
   * Auto-updated by TypeORM on every change.
   *
   * @type {Date}
   */
  @UpdateDateColumn({ type: 'datetime', default: () => 'CURRENT_TIMESTAMP' })
  updated_at: Date;

  /**
   * Account status flag.
   * Determines if the user account is active and can be used.
   * Defaults to false - accounts must be activated (e.g., email verification).
   *
   * @type {boolean}
   * @default false
   */
  @Column({ type: 'boolean', default: false })
  is_active: boolean;

  /**
   * Validates a plain text password against the stored hashed password.
   * Uses bcrypt.compare() for secure comparison that resists timing attacks.
   *
   * @async
   * @param {string} password - The plain text password to verify
   * @returns {Promise<boolean>} True if password matches, false otherwise
   * @example
   * const user = await userRepository.findOne(1);
   * const isValid = await user.validatePassword('myPassword123');
   * if (isValid) {
   *   // Login successful
   * }
   */
  async validatePassword(password: string): Promise<boolean> {
    return bcrypt.compare(password, this.password_hash);
  }

  /**
   * Hashes a plain text password using bcrypt algorithm.
   * Must be called before storing a password in the database.
   *
   * **Security Note**: 
   * - Salt rounds: 10 (recommended security/performance balance)
   * - Each call produces a different hash even for the same password
   * - Use this method in UserService during user creation and password updates
   *
   * @static
   * @async
   * @param {string} password - Plain text password to hash
   * @returns {Promise<string>} The hashed password ready for database storage
   * @throws {Error} If bcrypt hash fails (rare)
   * @example
   * const passwordHash = await User.hashPassword('securePassword123!');
   * // passwordHash = '$2b$10$...' (bcrypt hash format)
   */
  static async hashPassword(password: string): Promise<string> {
    const saltRounds = 10;
    return bcrypt.hash(password, saltRounds);
  }
}
